// <auto-generated />
using System;
using GW.Api.Data.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GW.Api.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230618162029_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GW.Api.Data.Models.MusicModel", b =>
                {
                    b.Property<int>("MusicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MusicId"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PlayListModelPlayListId")
                        .HasColumnType("integer");

                    b.Property<string>("TrackLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MusicId");

                    b.HasIndex("PlayListModelPlayListId");

                    b.ToTable("MusicModel");
                });

            modelBuilder.Entity("GW.Api.Data.Models.PlayListModel", b =>
                {
                    b.Property<int>("PlayListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PlayListId"));

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("integer");

                    b.Property<int?>("UserModelUserId")
                        .HasColumnType("integer");

                    b.HasKey("PlayListId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("PlayListModel");
                });

            modelBuilder.Entity("GW.Api.Data.Models.UserModel", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int?>("PlayListFavoritaPlayListId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("PlayListFavoritaPlayListId");

                    b.ToTable("UserModel");
                });

            modelBuilder.Entity("GW.Api.Data.Models.MusicModel", b =>
                {
                    b.HasOne("GW.Api.Data.Models.PlayListModel", null)
                        .WithMany("Musics")
                        .HasForeignKey("PlayListModelPlayListId");
                });

            modelBuilder.Entity("GW.Api.Data.Models.PlayListModel", b =>
                {
                    b.HasOne("GW.Api.Data.Models.UserModel", null)
                        .WithMany("PlayLists")
                        .HasForeignKey("UserModelUserId");
                });

            modelBuilder.Entity("GW.Api.Data.Models.UserModel", b =>
                {
                    b.HasOne("GW.Api.Data.Models.PlayListModel", "PlayListFavorita")
                        .WithMany()
                        .HasForeignKey("PlayListFavoritaPlayListId");

                    b.Navigation("PlayListFavorita");
                });

            modelBuilder.Entity("GW.Api.Data.Models.PlayListModel", b =>
                {
                    b.Navigation("Musics");
                });

            modelBuilder.Entity("GW.Api.Data.Models.UserModel", b =>
                {
                    b.Navigation("PlayLists");
                });
#pragma warning restore 612, 618
        }
    }
}
