version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.DB
    environment:
      - POSTGRES_PASSWORD=4Vfl4AtYdFMrxNq
      - POSTGRES_USER=Art
      - POSTGRES_DB=meu_postgres
    ports:
      - "5432:5432"
  api:
    build:
      context: ./src
      dockerfile: Dockerfile.API
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=4Vfl4AtYdFMrxNq
      - POSTGRES_USER=Art
      - POSTGRES_DB=meu_postgres
      - DB_CONNECTION_STRING=Host=db;Port=5432;Database=meu_postgres;Username=Art;Password=4Vfl4AtYdFMrxNq
    ports:
      - "80:80"