version: "3.9"
services:
  gw_db:
    build:
      context: .
      dockerfile: Dockerfile.DB
    environment:
      - POSTGRES_PASSWORD=4Vfl4AtYdFMrxNq
      - POSTGRES_USER=Art
      - POSTGRES_DB=meu_postgres
    ports:
      - "5432:5432"
  gw_api:
    build:
      context: ./src
      dockerfile: Dockerfile.API
    environment:
      - CONNECTION_STRING=Host=gw_db;Database=meu_postgres;Username=Art;Password=4Vfl4AtYdFMrxNq
    depends_on:
      - gw_db
    ports:
      - "80:80"